name: Compile SRS rule-sets from adguard
on:
  push:
    paths:
      - "url/list_url"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install sing-box
        run: |
          bash <(curl -fsSL https://sing-box.app/deb-install.sh)

      - name: Create output directory
        run: mkdir -p srs

      - name: Download files
        run: |
          wget -q -O blocklist.txt https://github.com/ppfeufer/adguard-filter-list/raw/refs/heads/master/blocklist
          done 

      - name: Convert downloaded files to SRS
        run: |
         for file in srs/*.txt; do
         filename=$(basename "$file" .txt)
         sing-box rule-set convert --type adguard --output "srs/${filename}.srs" "$file"
         done

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add srs/*.srs
          git commit -m "chore: auto-convert downloaded files to SRS files" || exit 0
          git push
